-- 1. Tabla grupos
CREATE TABLE IF NOT EXISTS public.grupos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL,
    descripcion TEXT,
    es_predeterminado BOOLEAN NOT NULL DEFAULT false,
    activo BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- Index único parcial para garantizar un solo grupo predeterminado
CREATE UNIQUE INDEX IF NOT EXISTS solo_un_predeterminado 
ON public.grupos (es_predeterminado) 
WHERE es_predeterminado = true;

-- 2. Tabla intermedia tareas_recurrentes
CREATE TABLE IF NOT EXISTS public.tareas_recurrentes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    grupo_id BIGINT NOT NULL REFERENCES public.grupos(id) ON DELETE CASCADE,
    tarea_id BIGINT NOT NULL REFERENCES public.tareas(id) ON DELETE CASCADE,
    orden INT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT now(),
    CONSTRAINT unique_grupo_tarea UNIQUE (grupo_id, tarea_id)
);

-- 3. Alterar checklist_tareas
ALTER TABLE public.checklist_tareas
ADD COLUMN IF NOT EXISTS foto_url TEXT,
ADD COLUMN IF NOT EXISTS foto_path TEXT;

-- 4. Supabase Storage (Crear bucket 'evidencias')
INSERT INTO storage.buckets (id, name, public)
VALUES ('evidencias', 'evidencias', true)
ON CONFLICT (id) DO UPDATE SET public = EXCLUDED.public;

-- Permitir a usuarios autenticados subir evidencia
CREATE POLICY "Authenticated users can upload evidencias"
ON storage.objects FOR INSERT TO authenticated 
WITH CHECK (bucket_id = 'evidencias');

-- Permitir a usuarios autenticados actualizar evidencia
CREATE POLICY "Authenticated users can update evidencias"
ON storage.objects FOR UPDATE TO authenticated 
USING (bucket_id = 'evidencias');

-- Permitir lectura pública (ya que el bucket es público)
CREATE POLICY "Public Access to evidencias"
ON storage.objects FOR SELECT 
USING (bucket_id = 'evidencias');

-- 5. Índices recomendados (rendimiento)
CREATE INDEX IF NOT EXISTS idx_checklists_colab_fecha
  ON public.checklists (colaborador_asignado_id, fecha);

CREATE INDEX IF NOT EXISTS idx_checklist_tareas_checklist
  ON public.checklist_tareas (checklist_id);

CREATE INDEX IF NOT EXISTS idx_tareas_recurrentes_grupo
  ON public.tareas_recurrentes (grupo_id);
